### ISSUE TITLE
Git-WhosMissing - Error on WSL 2

### ISSUE THREAD

**Issue by MrMichaelJKelly** [techdna/techdna-tools#1]
Run git-whosmissing on WSL 2
Result:
```
mikekell@MIKE3:/mnt/n/Artifacts$ cd /mnt/n/src
mikekell@MIKE3:/mnt/n/src$ git-whosmissing
Traceback (most recent call last):
  File "/home/mikekell/wsl_tools/bin/git-whosmissing", line 68, in <module>
    committers = subprocess.check_output(['git', 'shortlog', '-e', '--since=%s.months.ago' % months], text=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```

**Comment by MrMichaelJKelly** [comment]
Suspecting some inconsistency between subprocess on WSL 2 - or maybe a Python version thing?

**Comment by MrMichaelJKelly** [comment]
```
mikekell@MIKE3:/mnt/n/src$ python --version
Python 2.7.17
mikekell@MIKE3:/mnt/n/src$
```
Does it need to be Python 3?

**Comment by MrMichaelJKelly** [comment]
Per Martin:
I hit that recently as well, there was a “bad” git checkout - a directory that seems to be a git checkout, but when you cd to the dir, and try to run git commands, it errors out

Recommendations:
use git-who instead of git-whosmissing :slightly_smiling_face:
remove the .git-who.sqlite file between botched runs
run git-who -v init for a verbose run, you’ll see which git checkout breaks it
go look into that checkout …
